#!/usr/bin/env ruby

16.times do |i|
  fork { system <<HEREDOC }
echo "
import sys
sys.path.append('..')
import dataset
import torch
import random
dataset.generate_dataset('../datasets/spring/spring-#{i}.json',
                         (lambda x: x[:,0]**2+x[:,1]**2),
                         0., random.random()*2+1, 200,
                         torch.tensor([-.71,-.71]), torch.tensor([.71,.71]),
                         id=#{i})
" | python3
HEREDOC
end
